name: My Workflow

on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build container image
        run: |
          cd .github/actions/my-action
          docker build -t my-container-registry/my-action:latest .
      - name: Run python script
        uses: ./python.py
        with:
          MY_NAME: World
        run: python python.py ${{ inputs.MY_NAME }}
