name: My Workflow

on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build container image
        run: |
          cd .github/actions
          docker build -t my-container-registry/my-action:latest .
      - name: Run python script
        run: python python.py World
