name: My Workflow

on: [push]

inputs:
  # getting the value of a variable called MY_NAME.
  # Variable will be set in the workflow that runs this action.
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

branding:
  icon: "mic"
  color: "purple"

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build container image
        run: |
          cd .github/actions/my-action
          docker build -t my-container-registry/my-action:latest .
      - name: My Action
        uses: my-container-registry/my-action:latest
      - name: Run python script
        run: python python.py ${{ inputs.MY_NAME }}
